name: Bug report
description: Create a bug report for a STRAYED FATES: Forsaken
title: "[Bug]"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        This is for bug reports only. Check the project description and FAQ before posting; support questions should be redirected to our [Discord](https://discord.gg/HQ8Pqk8bUE).
  - type: input
    id: mc
    attributes:
      label: What Minecraft version(s) does this apply to?
      placeholder: ex. 1.8
    validations:
      required: true
  - type: input
    id: pack
    attributes:
      label: Project version
      description: What version of the project are you using?
      placeholder: ex. v1.0.0.2
    validations:
      required: true
  - type: dropdown
    id: format
    attributes:
      label: Mod or datapack version?
      options:
        - Datapack
        - Fabric/Quilt Mod
        - Neoforge/Forge Mod
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false
