modLoader="lowcodefml"
loaderVersion="[1,)"
license="LicenseRef-All-Rights-Reserved"
showAsResourcePack = false
issueTrackerURL="https://github.com/STRAYED-FATES/Forsaken/issues"

[[mods]]
    modId="strayed_fates_forsaken"
    version="1.1.3.2"
    displayName="STRAYED FATES: Forsaken"
    displayURL="https://modrinth.com/datapack/strayed-fates-forsaken"
    logoFile="pack.png"
    authors="TeraBuildsStuff"
    description="A collection of detailed abandoned Vanilla-friendly structures"
    updateJSONURL="https://api.modrinth.com/updates/3GGOgUqD/forge_updates.json"

[[dependencies.strayed_fates_forsaken]]
    modId="neoforge"
    mandatory=false
    versionRange="[20.2,20.6]"
    ordering="NONE"
    side="BOTH"
[[dependencies.strayed_fates_forsaken]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.20.6]"
    ordering="NONE"
    side="BOTH"